// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/service/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pb_service_service_proto protoreflect.FileDescriptor

const file_pb_service_service_proto_rawDesc = "" +
	"\n" +
	"\x18pb/service/service.proto\x12\n" +
	"pb.service\x1a\x16pb/service/story.proto\x1a\x1epb/service/story_request.proto2d\n" +
	"\fStoryService\x12T\n" +
	"\x16FindAllStoriesByUserID\x12%.pb.service.GetStoriesByUserIDRequest\x1a\x13.pb.service.StoriesB\fZ\n" +
	"pb/serviceb\x06proto3"

var file_pb_service_service_proto_goTypes = []any{
	(*GetStoriesByUserIDRequest)(nil), // 0: pb.service.GetStoriesByUserIDRequest
	(*Stories)(nil),                   // 1: pb.service.Stories
}
var file_pb_service_service_proto_depIdxs = []int32{
	0, // 0: pb.service.StoryService.FindAllStoriesByUserID:input_type -> pb.service.GetStoriesByUserIDRequest
	1, // 1: pb.service.StoryService.FindAllStoriesByUserID:output_type -> pb.service.Stories
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_service_service_proto_init() }
func file_pb_service_service_proto_init() {
	if File_pb_service_service_proto != nil {
		return
	}
	file_pb_service_story_proto_init()
	file_pb_service_story_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_service_service_proto_rawDesc), len(file_pb_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_service_service_proto_goTypes,
		DependencyIndexes: file_pb_service_service_proto_depIdxs,
	}.Build()
	File_pb_service_service_proto = out.File
	file_pb_service_service_proto_goTypes = nil
	file_pb_service_service_proto_depIdxs = nil
}
