// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/service/story.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Story struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	TagsId        []string               `protobuf:"bytes,8,rep,name=tags_id,json=tagsId,proto3" json:"tags_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Content       []*StoryElement        `protobuf:"bytes,7,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Story) Reset() {
	*x = Story{}
	mi := &file_pb_service_story_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_story_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_pb_service_story_proto_rawDescGZIP(), []int{0}
}

func (x *Story) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Story) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Story) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Story) GetTagsId() []string {
	if x != nil {
		return x.TagsId
	}
	return nil
}

func (x *Story) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Story) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Story) GetContent() []*StoryElement {
	if x != nil {
		return x.Content
	}
	return nil
}

type StoryElement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text            *string                `protobuf:"bytes,2,opt,name=text,proto3,oneof" json:"text,omitempty"`
	ParagraphStyles *ParagraphStyles       `protobuf:"bytes,3,opt,name=paragraph_styles,json=paragraphStyles,proto3,oneof" json:"paragraph_styles,omitempty"`
	Url             *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	ImageStyles     *ImageStyles           `protobuf:"bytes,5,opt,name=image_styles,json=imageStyles,proto3,oneof" json:"image_styles,omitempty"`
	Caption         *string                `protobuf:"bytes,6,opt,name=caption,proto3,oneof" json:"caption,omitempty"`
	AltText         *string                `protobuf:"bytes,7,opt,name=alt_text,json=altText,proto3,oneof" json:"alt_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoryElement) Reset() {
	*x = StoryElement{}
	mi := &file_pb_service_story_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryElement) ProtoMessage() {}

func (x *StoryElement) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_story_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryElement.ProtoReflect.Descriptor instead.
func (*StoryElement) Descriptor() ([]byte, []int) {
	return file_pb_service_story_proto_rawDescGZIP(), []int{1}
}

func (x *StoryElement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StoryElement) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *StoryElement) GetParagraphStyles() *ParagraphStyles {
	if x != nil {
		return x.ParagraphStyles
	}
	return nil
}

func (x *StoryElement) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *StoryElement) GetImageStyles() *ImageStyles {
	if x != nil {
		return x.ImageStyles
	}
	return nil
}

func (x *StoryElement) GetCaption() string {
	if x != nil && x.Caption != nil {
		return *x.Caption
	}
	return ""
}

func (x *StoryElement) GetAltText() string {
	if x != nil && x.AltText != nil {
		return *x.AltText
	}
	return ""
}

type Stories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stories       []*Story               `protobuf:"bytes,1,rep,name=Stories,proto3" json:"Stories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stories) Reset() {
	*x = Stories{}
	mi := &file_pb_service_story_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stories) ProtoMessage() {}

func (x *Stories) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_story_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stories.ProtoReflect.Descriptor instead.
func (*Stories) Descriptor() ([]byte, []int) {
	return file_pb_service_story_proto_rawDescGZIP(), []int{2}
}

func (x *Stories) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

type StoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stories       *Stories               `protobuf:"bytes,1,opt,name=stories,proto3" json:"stories,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoriesResponse) Reset() {
	*x = StoriesResponse{}
	mi := &file_pb_service_story_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoriesResponse) ProtoMessage() {}

func (x *StoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_story_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoriesResponse.ProtoReflect.Descriptor instead.
func (*StoriesResponse) Descriptor() ([]byte, []int) {
	return file_pb_service_story_proto_rawDescGZIP(), []int{3}
}

func (x *StoriesResponse) GetStories() *Stories {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *StoriesResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=NextCursor,proto3" json:"NextCursor,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pb_service_story_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_story_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pb_service_story_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *Metadata) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Metadata) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ParagraphStyles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FontSize      string                 `protobuf:"bytes,1,opt,name=font_size,json=fontSize,proto3" json:"font_size,omitempty"`
	FontStyle     string                 `protobuf:"bytes,2,opt,name=font_style,json=fontStyle,proto3" json:"font_style,omitempty"`
	FontFamily    string                 `protobuf:"bytes,3,opt,name=font_family,json=fontFamily,proto3" json:"font_family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParagraphStyles) Reset() {
	*x = ParagraphStyles{}
	mi := &file_pb_service_story_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParagraphStyles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParagraphStyles) ProtoMessage() {}

func (x *ParagraphStyles) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_story_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParagraphStyles.ProtoReflect.Descriptor instead.
func (*ParagraphStyles) Descriptor() ([]byte, []int) {
	return file_pb_service_story_proto_rawDescGZIP(), []int{5}
}

func (x *ParagraphStyles) GetFontSize() string {
	if x != nil {
		return x.FontSize
	}
	return ""
}

func (x *ParagraphStyles) GetFontStyle() string {
	if x != nil {
		return x.FontStyle
	}
	return ""
}

func (x *ParagraphStyles) GetFontFamily() string {
	if x != nil {
		return x.FontFamily
	}
	return ""
}

type ImageStyles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageSize     string                 `protobuf:"bytes,1,opt,name=image_size,json=imageSize,proto3" json:"image_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageStyles) Reset() {
	*x = ImageStyles{}
	mi := &file_pb_service_story_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageStyles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageStyles) ProtoMessage() {}

func (x *ImageStyles) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_story_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageStyles.ProtoReflect.Descriptor instead.
func (*ImageStyles) Descriptor() ([]byte, []int) {
	return file_pb_service_story_proto_rawDescGZIP(), []int{6}
}

func (x *ImageStyles) GetImageSize() string {
	if x != nil {
		return x.ImageSize
	}
	return ""
}

var File_pb_service_story_proto protoreflect.FileDescriptor

const file_pb_service_story_proto_rawDesc = "" +
	"\n" +
	"\x16pb/service/story.proto\x12\n" +
	"pb.service\x1a\x1apb/service/timestamp.proto\"\x8d\x02\n" +
	"\x05Story\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x17\n" +
	"\atags_id\x18\b \x03(\tR\x06tagsId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\acontent\x18\a \x03(\v2\x18.pb.service.StoryElementR\acontent\"\xef\x02\n" +
	"\fStoryElement\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x88\x01\x01\x12K\n" +
	"\x10paragraph_styles\x18\x03 \x01(\v2\x1b.pb.service.ParagraphStylesH\x01R\x0fparagraphStyles\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x02R\x03url\x88\x01\x01\x12?\n" +
	"\fimage_styles\x18\x05 \x01(\v2\x17.pb.service.ImageStylesH\x03R\vimageStyles\x88\x01\x01\x12\x1d\n" +
	"\acaption\x18\x06 \x01(\tH\x04R\acaption\x88\x01\x01\x12\x1e\n" +
	"\balt_text\x18\a \x01(\tH\x05R\aaltText\x88\x01\x01B\a\n" +
	"\x05_textB\x13\n" +
	"\x11_paragraph_stylesB\x06\n" +
	"\x04_urlB\x0f\n" +
	"\r_image_stylesB\n" +
	"\n" +
	"\b_captionB\v\n" +
	"\t_alt_text\"6\n" +
	"\aStories\x12+\n" +
	"\aStories\x18\x01 \x03(\v2\x11.pb.service.StoryR\aStories\"r\n" +
	"\x0fStoriesResponse\x12-\n" +
	"\astories\x18\x01 \x01(\v2\x13.pb.service.StoriesR\astories\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.pb.service.MetadataR\bmetadata\"\\\n" +
	"\bMetadata\x12\x1e\n" +
	"\n" +
	"NextCursor\x18\x01 \x01(\tR\n" +
	"NextCursor\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\x12\x18\n" +
	"\ahasMore\x18\x03 \x01(\bR\ahasMore\"n\n" +
	"\x0fParagraphStyles\x12\x1b\n" +
	"\tfont_size\x18\x01 \x01(\tR\bfontSize\x12\x1d\n" +
	"\n" +
	"font_style\x18\x02 \x01(\tR\tfontStyle\x12\x1f\n" +
	"\vfont_family\x18\x03 \x01(\tR\n" +
	"fontFamily\",\n" +
	"\vImageStyles\x12\x1d\n" +
	"\n" +
	"image_size\x18\x01 \x01(\tR\timageSizeB\fZ\n" +
	"pb/serviceb\x06proto3"

var (
	file_pb_service_story_proto_rawDescOnce sync.Once
	file_pb_service_story_proto_rawDescData []byte
)

func file_pb_service_story_proto_rawDescGZIP() []byte {
	file_pb_service_story_proto_rawDescOnce.Do(func() {
		file_pb_service_story_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_service_story_proto_rawDesc), len(file_pb_service_story_proto_rawDesc)))
	})
	return file_pb_service_story_proto_rawDescData
}

var file_pb_service_story_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_service_story_proto_goTypes = []any{
	(*Story)(nil),                 // 0: pb.service.Story
	(*StoryElement)(nil),          // 1: pb.service.StoryElement
	(*Stories)(nil),               // 2: pb.service.Stories
	(*StoriesResponse)(nil),       // 3: pb.service.StoriesResponse
	(*Metadata)(nil),              // 4: pb.service.Metadata
	(*ParagraphStyles)(nil),       // 5: pb.service.ParagraphStyles
	(*ImageStyles)(nil),           // 6: pb.service.ImageStyles
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_pb_service_story_proto_depIdxs = []int32{
	7, // 0: pb.service.Story.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: pb.service.Story.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: pb.service.Story.content:type_name -> pb.service.StoryElement
	5, // 3: pb.service.StoryElement.paragraph_styles:type_name -> pb.service.ParagraphStyles
	6, // 4: pb.service.StoryElement.image_styles:type_name -> pb.service.ImageStyles
	0, // 5: pb.service.Stories.Stories:type_name -> pb.service.Story
	2, // 6: pb.service.StoriesResponse.stories:type_name -> pb.service.Stories
	4, // 7: pb.service.StoriesResponse.metadata:type_name -> pb.service.Metadata
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pb_service_story_proto_init() }
func file_pb_service_story_proto_init() {
	if File_pb_service_story_proto != nil {
		return
	}
	file_pb_service_story_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_service_story_proto_rawDesc), len(file_pb_service_story_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_service_story_proto_goTypes,
		DependencyIndexes: file_pb_service_story_proto_depIdxs,
		MessageInfos:      file_pb_service_story_proto_msgTypes,
	}.Build()
	File_pb_service_story_proto = out.File
	file_pb_service_story_proto_goTypes = nil
	file_pb_service_story_proto_depIdxs = nil
}
